<?php
/**
 * Created by PhpStorm.
 * User: zhang han qing
 * Date: 2016/11/28
 * Time: 22:33
 */
namespace frontend\models;

use common\models\Feeds;
use yii\base\Model;

class FeedForm extends Model
{
    public $content;

    public $_lastError;
    public function rules()
    {
        return[
            ['content','required'],
            ['content','string','max'=>255]
        ];
    }
    public function attributeLabels()
    {
       // return parent::attributeLabels(); // TODO: Change the autogenerated stub
        return [
            'id'=>'ID',
            'content'=>'内容'
        ];
    }

    public function getList()
    {
        $model=new Feeds();
        $res=$model->find()->limit(10)->with('user')->orderBy(['id'=>SORT_DESC])->asArray()->all();
        return $res?:[];
    }

   public function create()
   {
       //创建留言保存
       try{
           $model=new Feeds();
           $model->user_id=\Yii::$app->user->identity->id;
           $model->content=$this->content;
           $model->created_at=time();
           var_dump($model);
           if(!$model->save()){
               throw new \Exception('保存失败');
           }
           return true;
       }catch (\Exception $e){
           $this->_lastError=$e->getMessage();
           return false;
       }
   }
}
