<?php
/**
 * Created by PhpStorm.
 * User: 97279
 * Date: 2016/11/22
 * Time: 18:46
 *基础控制器
*/
namespace frontend\controllers\base;

use yii\web\Controller;

class BaseController extends Controller{
    public function beforeAction($action)
    {
        if(!parent::beforeAction($action)){
            return false;
        }
        return true;
        //return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}